import streamlit as st
import urllib.parse

# --- 1. SESSION STATE & LOGIN LOGIC ---
if 'logged_in' not in st.session_state:
    st.session_state['logged_in'] = False
if 'page' not in st.session_state:
    st.session_state['page'] = "Login"

# --- 2. THE 20 PAGES FUNCTIONS ---
def login_page():
    st.markdown("<h1 style='text-align: center; color: #00FF41;'>PREDATOR AI LOGIN</h1>", unsafe_allow_html=True)
    with st.container():
        user = st.text_input("Admin Username")
        pwd = st.text_input("Access Key", type="password")
        if st.button("AUTHORIZE ACCESS"):
            if user == "divin" and pwd == "2026":
                st.session_state['logged_in'] = True
                st.session_state['page'] = "Dashboard"
                st.rerun()
            else:
                st.error("Access Denied: Invalid Credentials")

def dashboard():
    st.title("📊 Control Center")
    st.write("Welcome back, Agent Divin.")
    cols = st.columns(4)
    cols[0].metric("Target Scanned", "1,240")
    cols[1].metric("Active Deals", "12")
    cols[2].metric("Revenue (FRW)", "450,000")
    cols[3].metric("AI Efficiency", "98%")

# Service Pages Generators
def service_page(title, tool_link):
    st.title(f"🛠 {title}")
    st.write(f"Koresha iyi AI Tool gukora akazi k'umukiriya: [KANDA HANO]({tool_link})")
    biz_name = st.text_input(f"Izina rya Business ushakira {title}")
    if st.button(f"Generate {title} Draft"):
        st.success(f"Draft ya {title} kuri {biz_name} yiteguye!")

# --- 3. SIDEBAR NAVIGATION (THE 20 PAGES) ---
if st.session_state['logged_in']:
    with st.sidebar:
        st.image("https://cdn-icons-png.flaticon.com/512/2103/2103633.png", width=100)
        st.title("PREDATOR NAV")
        
        st.markdown("### 🎯 HUNTING")
        page = st.radio("Select Page", [
            "Dashboard", "Kigali Targets", "Rubavu Targets", "Musanze Targets", 
            "Huye Targets", "Instagram Scraper",
            "Website Builder", "Logo Designer", "Video Ads Creator", 
            "Menu Designer", "SEO Optimizer", "Copywriting AI",
            "WhatsApp Bot Creator", "Facebook Manager", "Google Maps Booster", 
            "Email Extractor", "Revenue Tracker", "User Settings", "AI Support", "Logout"
        ])
        st.session_state['page'] = page

# --- 4. PAGE ROUTING ENGINE ---
if st.session_state['page'] == "Login":
    login_page()
elif st.session_state['logged_in']:
    current = st.session_state['page']
    
    if current == "Dashboard": dashboard()
    elif "Targets" in current: 
        st.title(f"📍 {current}")
        st.write(f"Searching for businesses in {current.split()[0]} without digital presence...")
        st.table([{"Name": "Duka 1", "Problem": "No Website"}, {"Name": "Duka 2", "Problem": "Poor Logo"}])
    
    elif current == "Website Builder": service_page("Website Builder", "https://durable.co")
    elif current == "Logo Designer": service_page("Logo Designer", "https://looka.com")
    elif current == "Video Ads Creator": service_page("Video Creator", "https://invideo.io")
    elif current == "Menu Designer": service_page("Menu/Flyer Designer", "https://canva.com")
    elif current == "Revenue Tracker": 
        st.title("💰 Money Tracker")
        st.line_chart([100, 400, 200, 800, 500])
    elif current == "Logout":
        st.session_state['logged_in'] = False
        st.session_state['page'] = "Login"
        st.rerun()
    else:
        st.title(current)
        st.write(f"Content for {current} is being generated by AI...")
